# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [ "drm.edid_firmware=DP-3:edid/MonitorEDID.bin" "video=DP-3:e" "nvidia_drm.fbdev=1" "nvidia-drm.modeset=1" "nvidia.NVreg_PreserveVideoMemoryAllocations=1" ];
  hardware.firmware = [ (pkgs.runCommand "edid-firmware" { } ''
    mkdir -p $out/lib/firmware/edid
    cp ${./edid.bin} $out/lib/firmware/edid/MonitorEDID.bin
  '') ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/01bf5eef-5419-4b98-99c9-9cfb7f52b876";
    fsType = "ext4";
  };

  fileSystems."/srv/data" = {
    device = "/dev/disk/by-uuid/11E90BFF7F639C7F";
    fsType = "ntfs-3g";
    options = [ "permissions" "users" "uid=sciyoshi" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1F89-F6BB";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
